import { Roboto ,Science_Gothic} from "next/font/google";
import "./globals.css";

import Navbar from "@/components/layout/Navbar";
import Layoutwrapper from "@/components/layout/Layoutwrapper";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        
        <Layoutwrapper>

  {children}

        </Layoutwrapper>
      
        
        
        
        </body>
    </html>
  );
}